### ISSUE TITLE
Needs: calculate an approximate distance between two geohash points

### ISSUE THREAD

**Issue by harryprince** [Ironholds/geohash#5]
[pygeohash](https://github.com/wdm0006/pygeohash) have a function to calculate like this

```
 geohash_approximate_distance(geohash_1, geohash_2, check_validity=False)
        Returns the approximate great-circle distance between two geohashes in meters.

        :param geohash_1:
        :param geohash_2:
        :return:
```

**Comment by Ironholds** [comment]
Cool! I'll see what I can do.

**Comment by restonslacker** [comment]
@harryprince have you tried using the `geosphere` package for distance calculations?  I only ask because after looking at the pygeohash function, I would be wary of using it in general.  In the example below, the two points are less than 2 centimeters apart, but they share no characters in their geohash encoding so the function you describe would return 20,000,000 meters.

In my experience, `geosphere` is really fast.

``` r
geohash::gh_encode(45,0.0000001,10)                       
#> [1] "spbpbpbpbp"
geohash::gh_encode(45,-0.0000001,10)                      
#> [1] "ezzzzzzzzz"
geosphere::distHaversine(c(0.0000001,45),c(-0.0000001,45))
#> [1] 0.01574295
```

**Comment by Ironholds** [comment]
Good catch Seth!
